# Base configs
baseurl: "https://violetyao.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-145545931-1"

# UI configs
title: "Photos by Violet Yao"
subtitle: "See the world through my eyes!"
author: "Violet Yao"
header:
 title: "Photos"
 subtitle: "by Violet Yao"
footer:
 name: "I'm Violet Yao"
web_design: "AJ"
social_urls:
  linkedin: "https://in.linkedin.com/in/violetyao"
  github: "https://www.github.com/violetyao"
